image:
  name: texlive/texlive:latest
  entrypoint: ['/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0']

# this job builds the entire thesis
build-thesis:
  script:
    - make
  artifacts:
    paths:
      - "build/*.pdf"
