MSOURCES := thesis.tex \
			title.tex

CHDIRS := $(wildcard ch*)
CHSOURCES := $(wildcard ch*/chapter.tex)
SOURCES := $(MSOURCES) $(CHSOURCES)

.PHONY: all
all: build/thesis.pdf

build/thesis.pdf: $(SOURCES) diagrams conf.tex input.tex version.tex acknowledgements.tex title.tex
	@mkdir -p $(addprefix build/,$(CHDIRS))
	latexmk -outdir=build -pdf thesis.tex

conf.tex: $(wildcard conf/*.tex)
	@echo "%%% DO NOT EDIT THIS FILE! AUTO-GENERATED!" > $@
	cat $^ >> $@

input.tex: scripts/add-inputs.sh $(CHDIRS)
	@echo "%%% DO NOT EDIT THIS FILE! AUTO-GENERATED!" > $@
	./scripts/add-inputs.sh >> $@

.PHONY: FORCE
version.tex: FORCE
	@/bin/echo -E "\newcommand{\version}{$(shell git describe --always --long --dirty 2>/dev/null || echo "unknown")}" > $@

.PHONY: diagrams
diagrams:
	-$(foreach dir,$(CHDIRS),$(MAKE) -C $(dir) $@;)

.PHONY: install-hooks
install-hooks:
	@echo "installing git hooks into .git/hooks"

.PHONY: clean
clean:
	latexmk -outdir=build -C thesis.tex
	latexmk -outdir=build -C cover.tex
	$(RM) conf.tex input.tex
	$(RM) version.tex
